Repository dirigeants/klasa, pull requests merged in 2018-11, with the labels that each got.

#471 Settings rewrite
  CHANGELOG.md
  guides/Advanced SettingsGateway/SettingsGatewaySettingsUpdate.md
  guides/Advanced SettingsGateway/UnderstandingSchemaFolders.md
  src/commands/Admin/blacklist.js
  src/commands/Admin/conf.js
  src/commands/General/Chat Bot Info/help.js
  src/commands/General/User Settings/userconf.js
  src/events/guildCreate.js
  src/events/onceReady.js
  src/events/settingsUpdateEntry.js
  src/index.js
  src/inhibitors/disabled.js
  src/languages/en-US.js
  src/lib/Client.js
  src/lib/extensions/KlasaGuild.js
  src/lib/extensions/KlasaMessage.js
  src/lib/extensions/KlasaUser.js
  src/lib/schedule/Schedule.js
  src/lib/schedule/ScheduledTask.js
  src/lib/settings/Settings.js
  src/lib/settings/SettingsFolder.js
  src/lib/settings/gateway/Gateway.js
  src/lib/settings/gateway/GatewayDriver.js
  src/lib/settings/gateway/GatewayStorage.js
  src/lib/settings/schema/Schema.js
  src/lib/settings/schema/SchemaPiece.js
  src/lib/structures/Monitor.js
  src/lib/structures/Provider.js
  src/lib/structures/SQLProvider.js
  src/lib/usage/CommandUsage.js
  src/lib/util/constants.js
  src/lib/util/util.js
  src/monitors/commandHandler.js
  src/providers/json.js
  typings/index.d.ts
Labels: Meta: Refactor, Mod: SettingsGateway, SEM: Major, Type: Caching, Type: Enhancement

#476 fix: Settings cross-shard sync not setting existence flag to true
  src/events/settingsUpdateEntry.js
Labels: Meta: Backport, Meta: BugFix, Mod: SettingsGateway, Priority: Critical, SEM: Patch, Type: Caching

#475 feat: Added `KlasaClient#settingsSync` event.
  CHANGELOG.md
  guides/Included Pieces/IncludedEvents.md
  src/events/coreSettingsUpdate.js
  src/lib/Client.js
  src/lib/settings/Settings.js
  src/lib/settings/SettingsFolder.js
  src/lib/settings/gateway/Gateway.js
  typings/index.d.ts
Labels: Meta: Feature, Mod: SettingsGateway, SEM: Major, Type: Enhancement

#483 fix: Some finalizer errors fixed
  src/events/finalizerError.js
Labels: Meta: BugFix, SEM: Patch

#482 fix: CommandLogging finalizer not showing args
  src/finalizers/commandLogging.js
Labels: Meta: BugFix, SEM: Patch

#481 Pass empty string to task ID if not sharded
  src/lib/schedule/ScheduledTask.js
Labels: Meta: BugFix, SEM: Patch, Type: Sharding

#491 docs: Added typedef to Schema#add options parameter
  src/lib/settings/schema/Schema.js
Labels: Meta: Documentation, Mod: SettingsGateway, SEM: N/A

#499 src: Replace iOS quotes in eval
  src/commands/Admin/eval.js
Labels: Meta: Feature, Type: Enhancement

#501 refactor: Change overrides to be augmentations
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Typings, SEM: N/A, Type: Enhancement

#456 Changes to commandHandler's events
  src/lib/Client.js
  src/monitors/commandHandler.js
  typings/index.d.ts
Labels: Meta: Feature, SEM: Minor, Type: Enhancement, Type: Proposal

#448 Localize And Multiple Aborts Options
  src/languages/en-US.js
  src/lib/usage/TextPrompt.js
Labels: Meta: Feature, SEM: Minor

#506 typings: Added Message#send back
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Typings, SEM: Patch

#508 src: Remove Gateway#Settings, fix KlasaGatewaysOptions
  src/lib/settings/gateway/Gateway.js
  typings/index.d.ts
Labels: SEM: Major, Type: Enhancement

#488 PermissionLevels remove client
  guides/Getting Started/UnderstandingPermissionLevels.md
  src/lib/Client.js
  src/lib/permissions/PermissionLevels.js
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Refactor, Priority: Low, SEM: Major, Type: Enhancement

#511 feat: Added option for the JSON provider to change the baseDirectory
  src/providers/json.js
Labels: Meta: Feature, Mod: SettingsGateway, SEM: Minor, Type: Enhancement

#520 fix: Fixed array operations not removing element if it was the last
  src/lib/settings/SettingsFolder.js
  typings/index.d.ts
Labels: Meta: BugFix, Mod: SettingsGateway, SEM: Patch, Type: Caching
