Repository dirigeants/klasa, pull requests merged in 2018-05, with the labels that each got.

#289 fix: Hungry Hungry Hippos Eating Letters
  .github/ISSUE_TEMPLATE.md
Labels: Meta: Github, Type: Typo

#297 Await promise in member argument
  src/arguments/member.js
Labels: Meta: BugFix, Priority: High

#295 Update Application fetching
  src/events/onceReady.js
  src/lib/Client.js
Labels: Status: Blocked, Type: Caching, Type: Enhancement

#275 Fix typings
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: Documentation

#278 Made changes to eval cmd
  src/commands/Admin/eval.js
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Cleanup, Meta: Error Handling

#307 Fix broken language message
  src/arguments/message.js
  src/languages/en-US.js
Labels: Meta: BugFix, Type: Typo

#300 COMMAND_CONF_SERVER -> COMMAND_CONF_USER
  src/commands/General/User Configs/userconf.js
Labels: Meta: BugFix, Priority: High

#299 fix: Escape strings in Util#initClean
  CHANGELOG.md
  src/lib/util/util.js
Labels: Meta: BugFix, Priority: Medium, Status: Needs Testing, Type: Maintenance

#301 A little better grammar for multiple prefixes
  src/languages/en-US.js
Labels: Meta: BugFix, Type: Typo

#309 Rely on ScheduledTask state rather than Task state
  src/lib/schedule/ScheduledTask.js
  typings/index.d.ts
Labels: Meta: BugFix, Type: Caching

#314 add missing 'ignoreWebhooks' monitor config
  guides/Piece Basics/CreatingMonitors.md
Labels: Meta: Documentation, SEM: N/A

#306 Added QueryBuilder, exterminated all SQL from SettingGateway
  CHANGELOG.md
  guides/.docconfig.json
  guides/Advanced SettingGateway/UnderstandingSchemaFolders.md
  guides/Advanced SettingGateway/UnderstandingSchemaPieces.md
  guides/Piece Basics/CreatingArguments.md
  guides/Piece Basics/CreatingCommands.md
  guides/Piece Basics/CreatingEvents.md
  guides/Piece Basics/CreatingExtendables.md
  guides/Piece Basics/CreatingFinalizers.md
  guides/Piece Basics/CreatingInhibitors.md
  guides/Piece Basics/CreatingLanguages.md
  guides/Piece Basics/CreatingMonitors.md
  guides/Piece Basics/CreatingProviders.md
  guides/Piece Basics/CreatingSQLProviders.md
  guides/Piece Basics/CreatingTasks.md
  src/index.js
  src/lib/extensions/KlasaGuild.js
  src/lib/settings/Configuration.js
  src/lib/settings/Gateway.js
  src/lib/settings/GatewayStorage.js
  src/lib/settings/SchemaFolder.js
  src/lib/settings/SchemaPiece.js
  src/lib/structures/Provider.js
  src/lib/structures/SQLProvider.js
  src/lib/util/QueryBuilder.js
  src/lib/util/constants.js
  src/lib/util/util.js
  src/providers/json.js
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Feature, Meta: Refactor, Mod: SettingGateway, Type: Enhancement

#320 SG: Rename `$NAME_Schema.json` to `$NAME.schema.json`
  CHANGELOG.md
  src/lib/settings/GatewayStorage.js
Labels: Mod: SettingGateway, SEM: Major

#324 improve Util#deepClone
  src/lib/util/util.js
Labels: Meta: Refactor, Type: Enhancement, Type: Performance
