Repository dirigeants/klasa, pull requests merged in 2018-06, with the labels that each got.

#329 Make all props in ColorsFormatOptions optional
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Documentation

#284 [RFC] SGv2.2 - QueryBuilder and SQL abstraction
  CHANGELOG.md
  guides/.docconfig.json
  guides/Advanced SettingsGateway/SettingsGatewayConfigurationUpdate.md
  guides/Advanced SettingsGateway/SettingsGatewayKeyTypes.md
  guides/Advanced SettingsGateway/UnderstandingSchemaFolders.md
  guides/Advanced SettingsGateway/UnderstandingSchemaPieces.md
  guides/Building Your Bot/CreatingPointsSystems.md
  guides/Getting Started/UnderstandingSettingsGateway.md
  guides/Piece Basics/CreatingArguments.md
  guides/Piece Basics/CreatingCommands.md
  guides/Piece Basics/CreatingEvents.md
  guides/Piece Basics/CreatingExtendables.md
  guides/Piece Basics/CreatingFinalizers.md
  guides/Piece Basics/CreatingInhibitors.md
  guides/Piece Basics/CreatingLanguages.md
  guides/Piece Basics/CreatingMonitors.md
  guides/Piece Basics/CreatingProviders.md
  guides/Piece Basics/CreatingSQLProviders.md
  guides/Piece Basics/CreatingTasks.md
  src/events/onceReady.js
  src/index.js
  src/lib/Client.js
  src/lib/extensions/KlasaGuild.js
  src/lib/settings/Configuration.js
  src/lib/settings/Gateway.js
  src/lib/settings/GatewayDriver.js
  src/lib/settings/GatewayStorage.js
  src/lib/settings/Schema.js
  src/lib/settings/SchemaFolder.js
  src/lib/settings/SchemaPiece.js
  src/lib/structures/Provider.js
  src/lib/structures/SQLProvider.js
  src/lib/util/QueryBuilder.js
  src/lib/util/constants.js
  src/lib/util/util.js
  src/providers/json.js
  typings/index.d.ts
Labels: Meta: Backport, Meta: Feature, Meta: Refactor, Mod: SettingsGateway, Type: Enhancement

#325 [RFC] docs: Raw Event store
  guides/Other Subjects/PieceStores.md
Labels: Meta: Documentation, Meta: Examples, SEM: N/A

#335 Update Gateway.js
  src/lib/settings/Gateway.js
Labels: Meta: Documentation

#330 refactor: Gateway#sync, remove _download
  CHANGELOG.md
  src/events/onceReady.js
  src/lib/settings/Gateway.js
  src/lib/settings/GatewayDriver.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Cleanup, Meta: Refactor, Mod: SettingsGateway, Type: Consistency

#332 [RFC] Configuration#reset
  CHANGELOG.md
  src/lib/settings/Configuration.js
Labels: Meta: Refactor, Mod: SettingsGateway, Type: Performance

#331 [RFC] Gateway syncQueue
  CHANGELOG.md
  src/lib/settings/Configuration.js
  src/lib/settings/Gateway.js
  typings/index.d.ts
Labels: Meta: Feature, Mod: SettingsGateway, Type: Caching

#337 gooder grammers
  guides/Building Your Bot/CreatingPointsSystems.md
Labels: Meta: Documentation

#333 [RFC] Faster cross-shard synchronization
  CHANGELOG.md
  src/events/configUpdateEntry.js
  src/lib/Client.js
  src/lib/settings/Configuration.js
Labels: Meta: Cleanup, Meta: Refactor, Mod: SettingsGateway, Type: Enhancement

#334 docs: Muh templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/ISSUE.md
  .github/ISSUE_TEMPLATE/PROPOSAL.md
  .github/PULL_REQUEST_TEMPLATE/BUG_FIX.md
  .github/PULL_REQUEST_TEMPLATE/CHANGES.md
  .github/PULL_REQUEST_TEMPLATE/DOCUMENTATION.md
  .github/PULL_REQUEST_TEMPLATE/FEATURES.md
Labels: Meta: Github, Type: Enhancement

#342 fix: Configuration#update should never throw
  src/lib/settings/Configuration.js
Labels: Meta: BugFix, Meta: Error Handling, Mod: SettingsGateway

#346 Added ignoreBlacklistedUsers and ignoreBlacklistedGuilds Options
  guides/Included Pieces/IncludedInhibitors.md
  guides/Piece Basics/CreatingMonitors.md
  src/inhibitors/blacklisted.js
  src/lib/structures/Monitor.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Feature, Meta: Refactor, Type: Enhancement
