Repository dirigeants/klasa, pull requests merged in 2018-12, with the labels that each got.

#523 fix: messageDeleteBulk not sweeping
  src/events/messageDelete.js
  src/events/messageDeleteBulk.js
Labels: Meta: BugFix, Priority: High, SEM: Patch, Type: Caching

#530 typo: remove extra whitespace in RESOLVER_MINMAX_MIN
  src/languages/en-US.js
Labels: Meta: BugFix, SEM: Patch, Type: Typo

#532 make options in schedules.create() optional
  typings/index.d.ts
Labels: Meta: Typings, Priority: Low, SEM: N/A

#519 Localize And Multiple Repeat Prompt
  src/languages/en-US.js
  src/lib/usage/TextPrompt.js
Labels: Meta: Error Handling, Priority: Low, SEM: Patch, Type: Consistency

#529 readme: Replace Codacy with LGTM
  README.md
Labels: Meta: Documentation, SEM: N/A, Type: Maintenance

#472 docs: Fixed ReactionHandler time descriptions
  src/lib/util/ReactionHandler.js
Labels: Meta: Documentation, SEM: N/A, Type: Enhancement

#504 Different message for globally/guild disabled commands.
  src/inhibitors/disabled.js
  src/languages/en-US.js
Labels: Meta: Cleanup, SEM: Major, Type: Enhancement

#505 typings: Allow null for colors
  typings/index.d.ts
Labels: Meta: Documentation, SEM: N/A

#537 language: consistency
  src/languages/en-US.js
Labels: SEM: Patch, Type: Consistency

#539 Allows Inhibitors to have sync run methods
  src/inhibitors/cooldown.js
  src/inhibitors/disabled.js
  src/inhibitors/missingBotPermissions.js
  src/inhibitors/nsfw.js
  src/inhibitors/requiredSettings.js
  src/inhibitors/runIn.js
  src/inhibitors/slowmode.js
  src/lib/structures/Inhibitor.js
  src/lib/structures/InhibitorStore.js
  typings/index.d.ts
Labels: Meta: BugFix, Priority: Medium, SEM: Patch

#538 feature: Hidden Commands
  src/inhibitors/hidden.js
  src/lib/structures/Command.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Feature, Priority: Low, SEM: Minor, Type: Enhancement

#540 Correct some OOP placement of private methods
  src/lib/structures/Finalizer.js
  src/lib/structures/FinalizerStore.js
  src/lib/structures/Monitor.js
  src/lib/structures/MonitorStore.js
  typings/index.d.ts
Labels: Meta: BugFix, SEM: Patch, Type: Consistency, Type: Maintenance

#513 Fix inhibitor guide and type
  guides/Piece Basics/CreatingInhibitors.md
  typings/index.d.ts
Labels: Meta: Documentation, Meta: Typings, SEM: N/A, Type: Maintenance

#541 src: make piece serializer better and add aliases
  src/inhibitors/disabled.js
  src/languages/en-US.js
  src/serializers/piece.js
Labels: Meta: BugFix, Mod: SettingsGateway, SEM: Patch

#544 typings: Use interfaces where possible for all settings-related types
  typings/index.d.ts
Labels: Meta: Typings, SEM: N/A, Type: Enhancement

#543 grammar: language
  src/languages/en-US.js
Labels: Meta: BugFix, SEM: Patch, Type: Typo

#557 docs: Move ExecOptions to an external link to Node.js docs
  src/index.js
  src/lib/util/util.js
Labels: Meta: Documentation, SEM: N/A
