Repository dirigeants/klasa, pull requests merged in 2018-10, with the labels that each got.

#443 Various typo and grammar fixes Attempt 2
  guides/Advanced Commands/CommandsArguments.md
  guides/Advanced Commands/CommandsSubcommands.md
  guides/Advanced SettingsGateway/SettingsGatewaySettingsUpdate.md
  guides/Building Your Bot/CreatingPointsSystems.md
  guides/Getting Started/GettingStarted.md
  guides/Piece Basics/CreatingFinalizers.md
Labels: Meta: Documentation, SEM: N/A, Status: Changes Requested

#442 feat: RateLimitManager#acquire
  src/finalizers/commandCooldown.js
  src/inhibitors/slowmode.js
  src/lib/util/RateLimitManager.js
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Feature, SEM: Minor, Status: Review Ready

#453 languages: Fix missing capital letter
  src/languages/en-US.js
Labels: SEM: Patch, Type: Typo

#452 Changes So That Invite link dosent embed!
  src/languages/en-US.js
Labels: Meta: BugFix, SEM: Patch

#457 Fix `directory` arg name and documentation
  src/lib/structures/Command.js
  src/lib/structures/Event.js
  src/lib/structures/Inhibitor.js
  src/lib/structures/Monitor.js
Labels: Meta: BugFix, Meta: Documentation, SEM: Patch

#459 fix: GuildBlacklist failing at parsing external guilds
  src/commands/Admin/blacklist.js
  src/lib/Client.js
Labels: Meta: BugFix, Priority: Medium, SEM: Patch

#460 fix: Stringify errors
  src/commands/Admin/conf.js
Labels: Meta: BugFix, Meta: Error Handling, Priority: Medium, SEM: Patch

#463 Allow Managers to dynamically update child RateLimits
  src/lib/util/RateLimitManager.js
  typings/index.d.ts
Labels: Meta: Feature, Meta: Refactor, SEM: Minor, Type: Enhancement

#466 misc: Remove for-in loop in Colors.style
  src/lib/util/Colors.js
Labels: Meta: Cleanup, Priority: Low, SEM: Patch, Type: Typo

#464 Minor changes to UnderstandingSettingsGateway.md
  guides/Getting Started/UnderstandingSettingsGateway.md
Labels: Meta: Documentation, SEM: N/A, Type: Typo

#461 Fix prefix reminder bug
  src/monitors/commandHandler.js
Labels: Meta: BugFix, Priority: Low, SEM: Patch, Status: Changes Requested

#455 fullUsage consistency & improvement
  src/lib/usage/CommandUsage.js
Labels: Meta: BugFix, Priority: Low, SEM: Patch, Status: Changes Requested, Type: Consistency

#449 docs: Link to the correct thing
  guides/Advanced SettingsGateway/SettingsGatewayKeyTypes.md
Labels: Meta: Documentation, SEM: Patch, Status: Changes Requested, Type: Typo

#440 Update documentation
  guides/Getting Started/GettingStarted.md
Labels: Meta: Documentation, SEM: N/A, Status: Changes Requested

#437 Create multiple locale support patterns
  src/lib/util/Timestamp.js
  src/lib/util/constants.js
Labels: Meta: Feature, SEM: Minor, Type: Enhancement

#467 refactor: Convert GatewayDriver into a Collection<string, Gateway>
  CHANGELOG.md
  guides/Getting Started/UnderstandingSettingsGateway.md
  src/commands/Admin/conf.js
  src/commands/General/User Settings/userconf.js
  src/events/onceReady.js
  src/events/settingsUpdateEntry.js
  src/lib/extensions/KlasaGuild.js
  src/lib/extensions/KlasaMessage.js
  src/lib/extensions/KlasaUser.js
  src/lib/settings/GatewayDriver.js
  src/lib/util/QueryBuilder.js
  typings/index.d.ts
Labels: Meta: Refactor, Mod: SettingsGateway, SEM: Major, Type: Caching, Type: Enhancement

#468 add a/an support to Duration
  src/lib/util/Duration.js
Labels: Meta: BugFix, SEM: Patch

#445 typings: number[] and string[] are not valid types for color
  src/lib/util/Colors.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Typings, SEM: N/A, Status: Changes Requested

#469 Faster Duration
  src/lib/util/Duration.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Refactor, SEM: Patch, Type: Performance

#470 fix: Replace process.binding usage with native v8
  src/lib/util/Type.js
Labels: Meta: Refactor, Meta: V8, SEM: Patch, Type: Maintenance
