Repository dirigeants/klasa, pull requests merged in 2018-07, with the labels that each got.

#356 fix: Document Timestamp#displayUTC and patch it up
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Documentation

#355 fix: Schedule#delete
  CHANGELOG.md
  src/lib/schedule/Schedule.js
Labels: Meta: BugFix, Meta: Error Handling, Mod: SettingsGateway

#341 Plugin Support
  guides/.docconfig.json
  guides/Other Subjects/Plugins.md
  src/lib/Client.js
  typings/index.d.ts
Labels: Meta: Feature, Type: Enhancement

#336 Custom Member Gateway Tutorial.
  guides/.docconfig.json
  guides/Building Your Bot/CreatingACustomMemberGateway.md
Labels: Meta: Documentation, SEM: N/A, Type: Enhancement

#362 fix: JSON provider being inconsistent with other providers
  CHANGELOG.md
  src/lib/settings/Gateway.js
  src/lib/settings/GatewayDriver.js
  src/providers/json.js
  typings/index.d.ts
Labels: Meta: BugFix, Mod: SettingsGateway, Type: Caching

#360 Consistancy
  src/languages/en-US.js
Labels: Meta: Documentation

#339 [RFC] Updated and improved typings
  src/lib/Client.js
  src/lib/settings/GatewayDriver.js
  src/lib/settings/Schema.js
  src/lib/settings/SchemaFolder.js
  src/lib/settings/SchemaPiece.js
  src/lib/util/Colors.js
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Documentation

#343 rfc: Refactored Configuration
  CHANGELOG.md
  src/lib/settings/Configuration.js
  src/lib/settings/SchemaFolder.js
  src/lib/structures/base/Store.js
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Refactor, Mod: SettingsGateway, Type: Enhancement

#365 Multi Core Stores
  src/commands/Admin/load.js
  src/commands/Admin/transfer.js
  src/lib/Client.js
  src/lib/settings/GatewayStorage.js
  src/lib/structures/Language.js
  src/lib/structures/base/Piece.js
  src/lib/structures/base/Store.js
  src/providers/json.js
  typings/index.d.ts
Labels: Meta: Feature, Mod: Loader, SEM: Major, Type: Enhancement

#369 improve Timestamp#display() by 7-12%
  src/lib/util/Timestamp.js
  typings/index.d.ts
Labels: Meta: Refactor, SEM: Patch, Type: Performance

#370 Send locale
  src/commands/Admin/blacklist.js
  src/commands/Admin/conf.js
  src/commands/Admin/disable.js
  src/commands/Admin/eval.js
  src/commands/Admin/load.js
  src/commands/Admin/reboot.js
  src/commands/Admin/reload.js
  src/commands/Admin/transfer.js
  src/commands/Admin/unload.js
  src/commands/General/Chat Bot Info/help.js
  src/commands/General/Chat Bot Info/info.js
  src/commands/General/Chat Bot Info/invite.js
  src/commands/General/Chat Bot Info/ping.js
  src/commands/General/User Configs/userconf.js
  src/extendables/sendLocale.js
  src/languages/en-US.js
  src/lib/extensions/KlasaMessage.js
  src/monitors/commandHandler.js
  typings/index.d.ts
Labels: Meta: Feature, Type: Proposal

#372 Grammar fixes
  src/languages/en-US.js
Labels: Meta: Documentation, Type: Typo

#363 Add an option to reload all stores
  src/commands/Admin/reload.js
  src/languages/en-US.js
Labels: Type: Enhancement

#323 Remove all selfbot related checks
  CHANGELOG.md
  src/arguments/member.js
  src/arguments/user.js
  src/commands/General/Chat Bot Info/help.js
  src/commands/General/Chat Bot Info/invite.js
  src/events/onceReady.js
  src/languages/en-US.js
  src/lib/Client.js
  src/lib/parsers/Resolver.js
  src/lib/structures/Command.js
  src/lib/util/constants.js
  src/lib/util/util.js
  src/monitors/commandHandler.js
Labels: Meta: Cleanup, Status: Blocked, Type: Maintenance

#377 No more selfbots
  guides/Included Pieces/IncludedCommands.md
Labels: Meta: Documentation

#368 RFC: Even More SG Refactors
  src/lib/settings/Configuration.js
  src/lib/settings/Schema.js
  src/lib/settings/SchemaFolder.js
  src/lib/settings/SchemaPiece.js
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Refactor, Mod: SettingsGateway, Type: Consistency
