Repository dirigeants/klasa, pull requests merged in 2018-04, with the labels that each got.

#266 Fix quotedStringSupport types in typings
  typings/index.d.ts
Labels: Meta: Documentation, Type: Typo

#273 Update Store.js
  src/lib/structures/base/Store.js
Labels: Meta: Documentation

#272 Argument pieces
  guides/.docconfig.json
  guides/Other Subjects/PieceStores.md
  guides/Piece Basics/CreatingArguments.md
  src/arguments/argument.js
  src/arguments/boolean.js
  src/arguments/channel.js
  src/arguments/command.js
  src/arguments/custom.js
  src/arguments/date.js
  src/arguments/duration.js
  src/arguments/emoji.js
  src/arguments/event.js
  src/arguments/extendable.js
  src/arguments/finalizer.js
  src/arguments/float.js
  src/arguments/guild.js
  src/arguments/hyperlink.js
  src/arguments/inhibitor.js
  src/arguments/integer.js
  src/arguments/language.js
  src/arguments/literal.js
  src/arguments/member.js
  src/arguments/message.js
  src/arguments/monitor.js
  src/arguments/piece.js
  src/arguments/provider.js
  src/arguments/regexp.js
  src/arguments/role.js
  src/arguments/store.js
  src/arguments/string.js
  src/arguments/task.js
  src/arguments/time.js
  src/arguments/user.js
  src/commands/General/Chat Bot Info/help.js
  src/events/messageUpdate.js
  src/index.js
  src/lib/Client.js
  src/lib/parsers/ArgResolver.js
  src/lib/structures/Argument.js
  src/lib/structures/ArgumentStore.js
  src/lib/structures/Monitor.js
  src/lib/structures/MonitorStore.js
  src/lib/structures/base/Store.js
  src/lib/usage/TextPrompt.js
  src/lib/util/constants.js
Labels: Meta: Feature, Meta: Refactor, Type: Consistency, Type: Enhancement, Type: Performance

#276 Documented all changes for #272 and #260
  CHANGELOG.md
  guides/.docconfig.json
  guides/Included Pieces/IncludedArguments.md
  guides/Included Pieces/IncludedCommands.md
  guides/Included Pieces/IncludedEvents.md
  guides/Included Pieces/IncludedExtendables.md
  guides/Included Pieces/IncludedFinalizers.md
  guides/Included Pieces/IncludedInhibitors.md
  guides/Included Pieces/IncludedLanguages.md
  guides/Included Pieces/IncludedMonitors.md
  guides/Included Pieces/IncludedProviders.md
  guides/Included Pieces/IncludedTasks.md
  src/lib/structures/Argument.js
  typings/index.d.ts
Labels: Meta: Documentation, Type: Maintenance

#279 Fix float/num/number returning a string
  src/arguments/float.js
Labels: Meta: BugFix, Priority: Critical

#282 fix(Configuration): Clones lacking of id, update throwing synchronously
  src/lib/settings/Configuration.js
  src/lib/settings/GatewayStorage.js
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Error Handling, Priority: High

#286 Changed string literals to use flags
  src/extendables/attachable.js
  src/extendables/embedable.js
  src/extendables/postable.js
  src/extendables/readable.js
  src/inhibitors/missingBotPermissions.js
  src/lib/Client.js
  src/lib/extensions/KlasaMessage.js
Labels: Meta: Cleanup, Type: Performance
