Repository dirigeants/klasa, pull requests merged in 2018-02, with the labels that each got.

#182 Optimizations
  .travis-deploy.sh
  CHANGELOG.md
  guides/Other Subjects/PieceStores.md
  package.json
  src/commands/Admin/transfer.js
  src/extendables/sendCode.js
  src/extendables/sendEmbed.js
  src/extendables/sendFile.js
  src/extendables/sendFiles.js
  src/index.js
  src/lib/Client.js
  src/lib/extensions/KlasaMessage.js
  src/lib/settings/Gateway.js
  src/lib/settings/GatewayStorage.js
  src/lib/settings/SchemaPiece.js
  src/lib/structures/Command.js
  src/lib/structures/CommandStore.js
  src/lib/structures/Event.js
  src/lib/structures/EventStore.js
  src/lib/structures/Extendable.js
  src/lib/structures/ExtendableStore.js
  src/lib/structures/Finalizer.js
  src/lib/structures/FinalizerStore.js
  src/lib/structures/Inhibitor.js
  src/lib/structures/InhibitorStore.js
  src/lib/structures/Language.js
  src/lib/structures/LanguageStore.js
  src/lib/structures/Monitor.js
  src/lib/structures/MonitorStore.js
  src/lib/structures/Provider.js
  src/lib/structures/ProviderStore.js
  src/lib/structures/Task.js
  src/lib/structures/TaskStore.js
  src/lib/structures/base/Piece.js
  src/lib/structures/base/Store.js
  src/lib/usage/Tag.js
  src/lib/usage/TextPrompt.js
  typings/index.d.ts
Labels: Enhancement, Meta: Refactor

#187 Typo's
  guides/Piece Basics/CreatingCommands.md
Labels: Meta: BugFix, Meta: Documentation

#186 Added load command
  CHANGELOG.md
  src/commands/Admin/load.js
  src/languages/en-US.js
Labels: Meta: Feature

#184 Polish
  CHANGELOG.md
  guides/Getting Started/GettingStarted.md
  guides/Other Subjects/PieceStores.md
  package.json
  src/commands/Admin/disable.js
  src/commands/Admin/enable.js
  src/commands/Admin/load.js
  src/commands/Admin/reload.js
  src/commands/Admin/transfer.js
  src/commands/Admin/unload.js
  src/events/eventError.js
  src/events/finalizerError.js
  src/events/monitorError.js
  src/events/taskError.js
  src/index.js
  src/languages/en-US.js
  src/lib/Client.js
  src/lib/extensions/KlasaMessage.js
  src/lib/permissions/PermissionLevels.js
  src/lib/structures/Command.js
  src/lib/structures/CommandStore.js
  src/lib/structures/Event.js
  src/lib/structures/EventStore.js
  src/lib/structures/Extendable.js
  src/lib/structures/ExtendableStore.js
  src/lib/structures/Finalizer.js
  src/lib/structures/FinalizerStore.js
  src/lib/structures/Inhibitor.js
  src/lib/structures/InhibitorStore.js
  src/lib/structures/Language.js
  src/lib/structures/LanguageStore.js
  src/lib/structures/Monitor.js
  src/lib/structures/MonitorStore.js
  src/lib/structures/Provider.js
  src/lib/structures/ProviderStore.js
  src/lib/structures/Task.js
  src/lib/structures/TaskStore.js
  src/lib/structures/base/Piece.js
  src/lib/structures/base/Store.js
  src/lib/util/constants.js
  src/providers/json.js
  typings/index.d.ts
Labels: Enhancement, Meta: Refactor, WIP

#191 misc: 1 seconds again
  src/languages/en-US.js
Labels: Bug: Fixed, Meta: Documentation

#192 Performance boost
  src/commands/General/Chat Bot Info/help.js
  src/lib/structures/base/Store.js
  src/lib/util/util.js
  src/providers/collection.js
Labels: Enhancement, Meta: Refactor, PERF: Performance

#193 Documentation fixes
  src/lib/schedule/ScheduledTask.js
  src/lib/settings/SchemaFolder.js
  src/lib/structures/CommandStore.js
  src/lib/structures/Provider.js
  src/lib/structures/Task.js
Labels: Meta: Documentation, Type: Caching

#198 Typo (unneed -> unneeded)
  guides/Getting Started/UnderstandingPermissionLevels.md
Labels: Meta: Documentation, Type: Typo

#200 Fixed typings
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Documentation

#202 FIX(load command)
  src/commands/Admin/load.js
Labels: Meta: BugFix, Type: Typo

#201 misc: Improve util.toTitleCase
  CHANGELOG.md
  src/lib/util/util.js
  typings/index.d.ts
Labels: Type: Enhancement

#179 SettingGateway v2.1
  CHANGELOG.md
  guides/.docconfig.json
  guides/Advanced SettingGateway/SettingGatewayConfigurationUpdate.md
  guides/Advanced SettingGateway/SettingGatewayKeyTypes.md
  guides/Advanced SettingGateway/UnderstandingSchemaFolders.md
  guides/Advanced SettingGateway/UnderstandingSchemaPieces.md
  guides/Getting Started/UnderstandingSettingGateway.md
  package.json
  src/commands/Admin/conf.js
  src/commands/General/User Configs/userconf.js
  src/events/configUpdateEntry.js
  src/languages/en-US.js
  src/lib/Client.js
  src/lib/extensions/KlasaGuild.js
  src/lib/extensions/KlasaMessage.js
  src/lib/extensions/KlasaUser.js
  src/lib/parsers/ArgResolver.js
  src/lib/parsers/SettingResolver.js
  src/lib/permissions/PermissionLevels.js
  src/lib/schedule/Schedule.js
  src/lib/schedule/ScheduledTask.js
  src/lib/settings/Configuration.js
  src/lib/settings/Gateway.js
  src/lib/settings/GatewayDriver.js
  src/lib/settings/GatewayStorage.js
  src/lib/settings/SchemaFolder.js
  src/lib/settings/SchemaPiece.js
  src/lib/structures/Command.js
  src/lib/structures/Event.js
  src/lib/structures/Extendable.js
  src/lib/structures/Finalizer.js
  src/lib/structures/Inhibitor.js
  src/lib/structures/Language.js
  src/lib/structures/Monitor.js
  src/lib/structures/Provider.js
  src/lib/structures/Task.js
  src/lib/structures/base/Piece.js
  src/lib/usage/TextPrompt.js
  src/lib/util/Colors.js
  src/lib/util/KlasaConsole.js
  src/lib/util/ReactionHandler.js
  src/lib/util/RichDisplay.js
  src/lib/util/RichMenu.js
  src/lib/util/Timestamp.js
  src/lib/util/constants.js
  src/lib/util/util.js
  src/providers/collection.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Error Handling, Meta: Refactor, Type: Caching, Type: Enhancement, Type: Performance

#203 Fixed SettingResolver
  CHANGELOG.md
  src/lib/parsers/SettingResolver.js
Labels: Meta: BugFix, Priority: High

#204 Fixed `Util.getIdentifier` nullifying numbers.
  CHANGELOG.md
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: BugFix, Priority: High

#207 Fixed `Configuration#_parseSingle` not returning the modified array but the updated element
  CHANGELOG.md
  src/lib/settings/Configuration.js
Labels: Meta: BugFix, Priority: Critical

#196 Piece features
  CHANGELOG.md
  guides/Getting Started/UnderstandingCustomArguments.md
  guides/Included Pieces/IncludedEvents.md
  guides/Piece Basics/CreatingEvents.md
  guides/Piece Basics/CreatingExtendables.md
  guides/Piece Basics/CreatingMonitors.md
  guides/Piece Basics/CreatingTasks.md
  src/events/messageUpdate.js
  src/events/onceReady.js
  src/extendables/attachable.js
  src/extendables/embedable.js
  src/extendables/postable.js
  src/extendables/readable.js
  src/extendables/sendCode.js
  src/extendables/sendEmbed.js
  src/extendables/sendFile.js
  src/extendables/sendFiles.js
  src/extendables/sendMessage.js
  src/lib/Client.js
  src/lib/schedule/Schedule.js
  src/lib/schedule/ScheduledTask.js
  src/lib/structures/Event.js
  src/lib/structures/EventStore.js
  src/lib/structures/Extendable.js
  src/lib/structures/ExtendableStore.js
  src/lib/structures/Monitor.js
  src/lib/structures/MonitorStore.js
  src/lib/util/constants.js
  src/monitors/commandHandler.js
  typings/index.d.ts
Labels: Meta: Feature, Status: WIP, Type: Enhancement

#208 Grammar
  guides/Getting Started/UnderstandingPermissionLevels.md
Labels: Meta: Documentation
