Repository dirigeants/klasa, pull requests merged in 2018-08, with the labels that each got.

#380 Ao did a typo
  src/lib/structures/Command.js
Labels: Meta: BugFix, Type: Typo

#382 Add FAQ
  guides/.docconfig.json
  guides/Getting Started/faq.md
Labels: Meta: Documentation, Type: Enhancement

#385 refactor: Path cleanup
  src/lib/settings/Configuration.js
  src/lib/settings/Gateway.js
  src/lib/settings/schema/Base.js
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Feature, Meta: Refactor, Mod: SettingsGateway, Type: Enhancement, Type: Proposal

#374 SG: The Great Rename
  CHANGELOG.md
  README.md
  guides/.docconfig.json
  guides/Advanced SettingsGateway/SettingsGatewayKeyTypes.md
  guides/Advanced SettingsGateway/SettingsGatewaySettingsUpdate.md
  guides/Advanced SettingsGateway/UnderstandingSchemaFolders.md
  guides/Advanced SettingsGateway/UnderstandingSchemaPieces.md
  guides/Building Your Bot/CreatingACustomMemberGateway.md
  guides/Building Your Bot/CreatingPointsSystems.md
  guides/Getting Started/GettingStarted.md
  guides/Getting Started/UnderstandingPermissionLevels.md
  guides/Getting Started/UnderstandingSettingsGateway.md
  guides/Included Pieces/IncludedCommands.md
  guides/Included Pieces/IncludedEvents.md
  guides/Included Pieces/IncludedInhibitors.md
  guides/Other Subjects/RichMenu.md
  guides/Piece Basics/CreatingCommands.md
  guides/Piece Basics/CreatingEvents.md
  guides/Piece Basics/CreatingFinalizers.md
  guides/Piece Basics/CreatingInhibitors.md
  guides/Piece Basics/CreatingLanguages.md
  guides/Piece Basics/CreatingMonitors.md
  guides/Piece Basics/CreatingProviders.md
  guides/Piece Basics/CreatingSQLProviders.md
  guides/Piece Basics/CreatingTasks.md
  src/commands/Admin/blacklist.js
  src/commands/Admin/conf.js
  src/commands/General/Chat Bot Info/help.js
  src/commands/General/User Settings/userconf.js
  src/events/configUpdateEntry.js
  src/events/guildCreate.js
  src/events/guildDelete.js
  src/events/onceReady.js
  src/index.js
  src/inhibitors/disabled.js
  src/inhibitors/requiredConfigs.js
  src/inhibitors/requiredSettings.js
  src/languages/en-US.js
  src/lib/Client.js
  src/lib/extensions/KlasaGuild.js
  src/lib/extensions/KlasaMessage.js
  src/lib/extensions/KlasaUser.js
  src/lib/schedule/Schedule.js
  src/lib/schedule/ScheduledTask.js
  src/lib/settings/Gateway.js
  src/lib/settings/GatewayDriver.js
  src/lib/settings/SchemaFolder.js
  src/lib/settings/SchemaPiece.js
  src/lib/settings/Settings.js
  src/lib/structures/Command.js
  src/lib/structures/Monitor.js
  src/lib/structures/Provider.js
  src/lib/structures/SQLProvider.js
  src/lib/usage/CommandUsage.js
  src/lib/util/constants.js
  src/monitors/commandHandler.js
  typings/index.d.ts
Labels: Mod: SettingsGateway, SEM: Major, Type: Consistency

#388 docs: Fixed KlasaConsoleColorStyles not having optionals
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Documentation

#395 fix: Reboot should shutdown providers
  src/commands/Admin/reboot.js
Labels: Meta: BugFix, SEM: Patch, Status: Review Ready

#392 feat: Support for no prefix
  CHANGELOG.md
  guides/Getting Started/GettingStarted.md
  src/lib/Client.js
  src/lib/util/constants.js
  src/monitors/commandHandler.js
  typings/index.d.ts
Labels: Meta: Feature, SEM: Minor, Status: Review Ready, Type: Enhancement

#391 feat: Remove second cache layer from Gateway
  CHANGELOG.md
  guides/.docconfig.json
  guides/Building Your Bot/CreatingACustomMemberGateway.md
  src/events/onceReady.js
  src/events/settingsUpdateEntry.js
  src/lib/settings/Gateway.js
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: BugFix, Mod: SettingsGateway, SEM: Minor, Status: Review Ready, Type: Caching

#398 feat: Added overwrite action, allow add/remove/auto to update multiple entries
  CHANGELOG.md
  guides/Advanced SettingsGateway/SettingsGatewaySettingsUpdate.md
  src/lib/settings/Settings.js
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: Feature, Mod: SettingsGateway, SEM: Major, Status: Needs Testing, Type: Enhancement

#399 Capitalization /tableflip
  src/languages/en-US.js
Labels: SEM: N/A, Type: Typo

#383 Schema Changes
  CHANGELOG.md
  guides/.docconfig.json
  guides/Advanced SettingsGateway/SettingsGatewayKeyTypes.md
  guides/Advanced SettingsGateway/SettingsGatewaySettingsUpdate.md
  guides/Advanced SettingsGateway/UnderstandingSchemaFolders.md
  guides/Advanced SettingsGateway/UnderstandingSchemaPieces.md
  guides/Building Your Bot/CreatingACustomMemberGateway.md
  guides/Building Your Bot/CreatingPointsSystems.md
  guides/Getting Started/GettingStarted.md
  guides/Getting Started/UnderstandingSettingsGateway.md
  guides/Included Pieces/IncludedEvents.md
  guides/Piece Basics/CreatingProviders.md
  guides/Piece Basics/CreatingSQLProviders.md
  src/commands/Admin/conf.js
  src/events/onceReady.js
  src/events/settingsUpdateEntry.js
  src/index.js
  src/languages/en-US.js
  src/lib/Client.js
  src/lib/parsers/Resolver.js
  src/lib/parsers/SettingResolver.js
  src/lib/settings/Gateway.js
  src/lib/settings/GatewayDriver.js
  src/lib/settings/GatewayStorage.js
  src/lib/settings/Schema.js
  src/lib/settings/SchemaFolder.js
  src/lib/settings/SchemaPiece.js
  src/lib/settings/Settings.js
  src/lib/settings/schema/Base.js
  src/lib/settings/schema/Schema.js
  src/lib/settings/schema/SchemaFolder.js
  src/lib/settings/schema/SchemaPiece.js
  src/lib/settings/schema/types/Boolean.js
  src/lib/settings/schema/types/Channel.js
  src/lib/settings/schema/types/Guild.js
  src/lib/settings/schema/types/Number.js
  src/lib/settings/schema/types/Piece.js
  src/lib/settings/schema/types/Role.js
  src/lib/settings/schema/types/String.js
  src/lib/settings/schema/types/Url.js
  src/lib/settings/schema/types/User.js
  src/lib/settings/schema/types/base/SchemaType.js
  src/lib/settings/schema/types/base/SchemaTypes.js
  src/lib/settings/schema/types/index.js
  src/lib/structures/Provider.js
  src/lib/structures/SQLProvider.js
  src/lib/util/constants.js
  src/lib/util/util.js
  src/monitors/commandHandler.js
  src/providers/json.js
  typings/index.d.ts
Labels: Meta: Refactor, Mod: SettingsGateway, SEM: Major, Status: Ready To Merge, Type: Enhancement

#400 polish: Schedule and ScheduledTask
  src/lib/schedule/Schedule.js
  src/lib/schedule/ScheduledTask.js
Labels: Meta: Cleanup, SEM: Patch, Type: Enhancement

#404 fix: A 9-month old bug
  src/events/guildDelete.js
Labels: Meta: BugFix, Priority: High, SEM: N/A, Type: Typo

#405 Fix Util.objectToTuples
  src/lib/util/util.js
Labels: Meta: BugFix, Priority: High, SEM: Patch

#408 Cooldown Refactor
  src/finalizers/commandCooldown.js
  src/index.js
  src/inhibitors/cooldown.js
  src/lib/extensions/KlasaMessage.js
  src/lib/structures/Command.js
  src/lib/util/RateLimit.js
  src/lib/util/RateLimitManager.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Feature, Meta: Refactor, SEM: Minor, Type: Caching

#409 fix: isThenable returning true on Promise constructor
  src/lib/util/util.js
Labels: Meta: BugFix, SEM: Patch
