Repository dirigeants/klasa, pull requests merged in 2018-09, with the labels that each got.

#411 Serializers
  guides/.docconfig.json
  guides/Included Pieces/IncludedArguments.md
  guides/Included Pieces/IncludedCommands.md
  guides/Included Pieces/IncludedEvents.md
  guides/Included Pieces/IncludedExtendables.md
  guides/Included Pieces/IncludedFinalizers.md
  guides/Included Pieces/IncludedInhibitors.md
  guides/Included Pieces/IncludedLanguages.md
  guides/Included Pieces/IncludedMonitors.md
  guides/Included Pieces/IncludedProviders.md
  guides/Included Pieces/IncludedSerializers.md
  guides/Included Pieces/IncludedTasks.md
  guides/Piece Basics/CreatingArguments.md
  guides/Piece Basics/CreatingCommands.md
  guides/Piece Basics/CreatingEvents.md
  guides/Piece Basics/CreatingExtendables.md
  guides/Piece Basics/CreatingFinalizers.md
  guides/Piece Basics/CreatingInhibitors.md
  guides/Piece Basics/CreatingLanguages.md
  guides/Piece Basics/CreatingMonitors.md
  guides/Piece Basics/CreatingProviders.md
  guides/Piece Basics/CreatingSQLProviders.md
  guides/Piece Basics/CreatingSerializers.md
  guides/Piece Basics/CreatingTasks.md
  src/index.js
  src/lib/Client.js
  src/lib/schedule/Schedule.js
  src/lib/schedule/ScheduledTask.js
  src/lib/settings/GatewayStorage.js
  src/lib/settings/Settings.js
  src/lib/settings/schema/Base.js
  src/lib/settings/schema/SchemaPiece.js
  src/lib/settings/schema/types/Boolean.js
  src/lib/settings/schema/types/Channel.js
  src/lib/settings/schema/types/Guild.js
  src/lib/settings/schema/types/Number.js
  src/lib/settings/schema/types/Piece.js
  src/lib/settings/schema/types/Role.js
  src/lib/settings/schema/types/String.js
  src/lib/settings/schema/types/Url.js
  src/lib/settings/schema/types/User.js
  src/lib/settings/schema/types/base/SchemaType.js
  src/lib/settings/schema/types/base/SchemaTypes.js
  src/lib/settings/schema/types/index.js
  src/lib/structures/Serializer.js
  src/lib/structures/SerializerStore.js
  src/lib/util/constants.js
  src/serializers/any.js
  src/serializers/boolean.js
  src/serializers/channel.js
  src/serializers/guild.js
  src/serializers/number.js
  src/serializers/piece.js
  src/serializers/role.js
  src/serializers/string.js
  src/serializers/url.js
  src/serializers/user.js
  typings/index.d.ts
Labels: Meta: Feature, Mod: SettingsGateway, SEM: Major, Status: Ready To Merge

#416 feat: Added `KlasaClientOptions.createPiecesFolders`
  CHANGELOG.md
  src/lib/Client.js
  src/lib/structures/LanguageStore.js
  src/lib/structures/base/Store.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Feature, Mod: Loader, SEM: Minor, Type: Enhancement

#418 add slowmode options and inhibitor to core
  src/inhibitors/slowmode.js
  src/lib/Client.js
  src/lib/util/RateLimit.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Feature, SEM: Minor, Type: Enhancement

#419 src: Cleanup schemas
  src/commands/Admin/conf.js
  src/commands/General/User Settings/userconf.js
  src/lib/settings/schema/Base.js
  src/lib/settings/schema/Schema.js
  src/lib/settings/schema/SchemaFolder.js
  typings/index.d.ts
Labels: Meta: Cleanup, Mod: SettingsGateway, SEM: Minor, Type: Consistency

#424 Fix typo in docs
  guides/Piece Basics/CreatingArguments.md
Labels: Meta: Documentation, SEM: N/A, Type: Typo

#423 Add MultiArguments for all d.js and klasa structures
  src/arguments/arguments.js
  src/arguments/channels.js
  src/arguments/commands.js
  src/arguments/emojis.js
  src/arguments/events.js
  src/arguments/extendables.js
  src/arguments/finalizers.js
  src/arguments/guilds.js
  src/arguments/inhibitors.js
  src/arguments/languages.js
  src/arguments/members.js
  src/arguments/messages.js
  src/arguments/monitors.js
  src/arguments/pieces.js
  src/arguments/providers.js
  src/arguments/roles.js
  src/arguments/stores.js
  src/arguments/tasks.js
  src/arguments/users.js
  src/index.js
  src/languages/en-US.js
  src/lib/structures/MultiArgument.js
  typings/index.d.ts
Labels: Meta: Feature, Mod: Parser, SEM: Minor, Type: Enhancement

#427 Fix potentially duplicated plugins from being loaded
  src/lib/Client.js
Labels: Meta: BugFix, Meta: Cleanup, SEM: Patch, Type: Enhancement

#430 Update Provider.js
  src/lib/structures/Provider.js
Labels: Meta: Documentation, SEM: N/A, Type: Typo

#406 wip: update message handling to utilize send rewrite
  src/extendables/SendAliases.js
  src/lib/extensions/KlasaMessage.js
  typings/index.d.ts
Labels: Meta: Dependencies, Meta: Refactor, Type: Enhancement

#429 Restore original property descriptors
  src/lib/structures/Extendable.js
  typings/index.d.ts
Labels: Meta: BugFix, SEM: Patch

#412 Cleanup
  src/arguments/user.js
  src/commands/Admin/blacklist.js
  src/commands/Admin/conf.js
  src/commands/Admin/load.js
  src/commands/Admin/reload.js
  src/commands/General/User Settings/userconf.js
  src/extendables/SendAliases.js
  src/finalizers/commandCooldown.js
  src/index.js
  src/inhibitors/cooldown.js
  src/inhibitors/disabled.js
  src/inhibitors/missingBotPermissions.js
  src/inhibitors/permissions.js
  src/inhibitors/requiredSettings.js
  src/inhibitors/runIn.js
  src/languages/en-US.js
  src/lib/extensions/KlasaMessage.js
  src/lib/permissions/PermissionLevels.js
  src/lib/settings/Settings.js
  src/lib/structures/Argument.js
  src/lib/structures/ArgumentStore.js
  src/lib/structures/Command.js
  src/lib/structures/CommandStore.js
  src/lib/structures/Finalizer.js
  src/lib/structures/Language.js
  src/lib/structures/MultiArgument.js
  src/lib/structures/Provider.js
  src/lib/structures/Serializer.js
  src/lib/structures/SerializerStore.js
  src/lib/structures/Task.js
  src/lib/structures/base/AliasPiece.js
  src/lib/structures/base/AliasStore.js
  src/lib/structures/base/Piece.js
  src/lib/structures/base/Store.js
  src/lib/usage/CommandUsage.js
  src/lib/usage/Tag.js
  src/lib/usage/TextPrompt.js
  src/lib/usage/Usage.js
  src/lib/util/RateLimitManager.js
  src/lib/util/constants.js
  src/monitors/commandHandler.js
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Refactor, SEM: Minor, Type: Enhancement

#431 Remove useless stuff from Colors
  src/lib/util/Colors.js
Labels: Meta: Cleanup, Priority: Low, SEM: Major, Status: Needs Typings
