Repository dirigeants/klasa, pull requests merged in 2018-03, with the labels that each got.

#211 Silly edit, but capitalised Klasa
  README.md
Labels: Meta: Documentation, Type: Typo

#212 Fixed overloading for Configuration#update
  src/lib/settings/Configuration.js
Labels: Meta: BugFix

#213 Convert object instance to Symbol and add PermissionLevels#remove()
  CHANGELOG.md
  src/lib/permissions/PermissionLevels.js
  typings/index.d.ts
Labels: Meta: Feature, Type: Enhancement

#215 fix: Message#send with embed objects
  src/lib/extensions/KlasaMessage.js
Labels: Meta: BugFix

#217 Getters return null
  src/lib/Client.js
  src/lib/extensions/KlasaGuild.js
  src/lib/schedule/ScheduledTask.js
  src/lib/settings/GatewayStorage.js
  src/lib/structures/LanguageStore.js
  src/lib/structures/ProviderStore.js
  typings/index.d.ts
Labels: Type: Enhancement

#218 Add more sense to UnderstandingSettingGateway.md
  guides/Getting Started/UnderstandingSettingGateway.md
Labels: Meta: Documentation

#222 fix Rich Menu Example
  guides/Other Subjects/RichMenu.md
Labels: Meta: BugFix

#221 Settings Queued and Initialized Before Login
  src/events/onceReady.js
  src/lib/Client.js
  src/lib/settings/GatewayDriver.js
  typings/index.d.ts
Labels: Meta: BugFix

#225 Duplication
  src/lib/settings/SchemaFolder.js
  src/lib/util/constants.js
Labels: Meta: Refactor, Type: Enhancement

#230 Fixes SQL Database bugs
  src/lib/settings/Configuration.js
  src/lib/settings/SchemaFolder.js
Labels: Meta: BugFix

#232 fix typo in monitor
  guides/Other Subjects/CreatingPointsSystems.md
Labels: Meta: Documentation, Type: Typo

#227 Colors rewrite
  CHANGELOG.md
  src/finalizers/commandlogging.js
  src/lib/Client.js
  src/lib/util/Colors.js
  src/lib/util/KlasaConsole.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Refactor, Type: Enhancement, Type: Performance

#231 Change initTable method to pass raw sql Schema to provider
  src/lib/settings/GatewayStorage.js
Labels: Meta: BugFix

#226 Added CreatingPointsSystems.md to the guides
  guides/.docconfig.json
  guides/Building Your Bot/CreatingPointsSystems.md
Labels: Meta: Documentation, Meta: Examples

#234 Add @extends Schema to SchemaFolder & SchemaPiece
  src/lib/settings/SchemaFolder.js
  src/lib/settings/SchemaPiece.js
Labels: Meta: BugFix, Meta: Documentation

#233 Get undefined key
  src/commands/Admin/conf.js
  src/commands/General/User Configs/userconf.js
Labels: Meta: BugFix, Meta: Error Handling, Priority: High

#235 Fix command editing deleted messages
  src/events/messageDelete.js
  src/events/messageDeleteBulk.js
  src/index.js
  src/lib/Client.js
  src/lib/extensions/KlasaMessage.js
  src/lib/parsers/Resolver.js
  src/lib/settings/Configuration.js
  src/lib/structures/base/Piece.js
  src/providers/json.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Error Handling, Priority: High, Type: Caching

#239 Fixed critical bugs in SettingGateway
  src/lib/settings/Gateway.js
Labels: Meta: BugFix, Priority: Critical, Type: Typo

#238 Minor usage refactor for readability and (probably) performance
  src/lib/usage/Tag.js
  src/lib/usage/Usage.js
  typings/index.d.ts
Labels: Meta: Refactor, Type: Performance

#243 Typo/Changed method
  guides/Getting Started/UnderstandingPermissionLevels.md
Labels: Meta: Documentation, Type: Typo

#245 fix optional repeating
  src/lib/usage/TextPrompt.js
Labels: Meta: BugFix, Meta: Refactor

#251 Fix Circulars in Console and Type
  src/commands/Admin/eval.js
  src/events/log.js
  src/index.js
  src/lib/Client.js
  src/lib/util/KlasaConsole.js
  src/lib/util/Type.js
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Refactor, Type: Maintenance

#252 Updated ScheduledTask to also pass ID
  src/lib/schedule/ScheduledTask.js
Labels: Type: Enhancement

#253 Fix(Usage): Accidental trimming
  src/lib/usage/TextPrompt.js
  typings/index.d.ts
Labels: Meta: BugFix, Priority: Low
