Repository dirigeants/klasa, pull requests merged in 2019-08, with the labels that each got.

#784 Client.use should use the util class
  src/lib/Client.js
Labels: Meta: Refactor, SEM: Patch, Type: Enhancement

#763 Cooldown Inhibitor Change Seconds To Formatted String
  src/inhibitors/cooldown.js
  src/languages/en-US.js
Labels: SEM: Patch

#762 perf(Timestamp): Increased performance and move patterns to maps
  src/lib/util/Timestamp.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Refactor, Meta: V8, SEM: Major, Type: Performance
