Repository dirigeants/klasa, pull requests merged in 2019-02, with the labels that each got.

#556 typings: Refactor and fixed augmentations
  src/lib/settings/GatewayDriver.js
  src/lib/util/KlasaConsole.js
  src/lib/util/RichMenu.js
  src/lib/util/util.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Cleanup, Meta: Documentation, Meta: Typings, SEM: N/A, Type: Enhancement

#582 chore(engines): Require Node.js >=10.1.0
  .travis.yml
  package.json
Labels: Meta: Dependencies, SEM: N/A, Type: Maintenance

#578 deps: Prepare Klasa for incoming breaking change
  src/events/messageUpdate.js
  src/extendables/MessageExtendables.js
  src/extendables/SendAliases.js
  src/finalizers/commandLogging.js
  src/index.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Dependencies, SEM: Major, Type: Maintenance

#587 typings: Fixed two interfaces
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Typings, SEM: Patch

#577 misc: Remove duplicate cancel prompt options
  src/languages/en-US.js
  src/lib/usage/TextPrompt.js
Labels: Meta: Cleanup, Priority: Low

#594 fix: Default data not being initialized
  src/lib/settings/Settings.js
  src/lib/settings/SettingsFolder.js
  src/lib/settings/gateway/GatewayStorage.js
  typings/index.d.ts
Labels: Meta: BugFix, Mod: SettingsGateway, Priority: High, SEM: Patch, Status: Ready To Merge

#595 docs: Fixed typos in RateLimit{Manager}
  src/lib/util/RateLimit.js
  src/lib/util/RateLimitManager.js
Labels: Meta: Documentation, SEM: N/A, Type: Maintenance
