Repository dirigeants/klasa, pull requests merged in 2019-10, with the labels that each got.

#825 Fix AliasStore docs
  src/lib/structures/base/AliasStore.js
Labels: Meta: Documentation, SEM: N/A, Type: Typo

#828 Settings Options namespace
  src/events/coreGuildDelete.js
  src/lib/Client.js
  src/lib/settings/SettingsFolder.js
  src/lib/settings/gateway/GatewayDriver.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Feature, Mod: SettingsGateway, SEM: Major, Status: Ready To Merge

#836 Fix: access client properly part 2
  src/lib/settings/SettingsFolder.js
Labels: Meta: BugFix, Mod: SettingsGateway, Priority: Critical, SEM: Patch

#835 Revert "Cooldown Inhibitor Change Seconds To Formatted String"
  src/inhibitors/cooldown.js
  src/languages/en-US.js
Labels: Meta: BugFix

#840 Fix: Gateway typings.
  typings/index.d.ts
Labels: Meta: Typings, Mod: SettingsGateway

#841 fix: Remove deepClone on SettingsFolder#get
  src/lib/settings/SettingsFolder.js
Labels: Meta: BugFix, Mod: SettingsGateway, Priority: High, SEM: Major

#844 Settings sqlp fixes
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Typings, Mod: SettingsGateway, SEM: N/A

#855 Fix Store#get typings
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Typings, SEM: N/A
