Repository dirigeants/klasa, pull requests merged in 2019-06, with the labels that each got.

#712 fix(docs): change ScheduledTask#catchUp to a boolean
  src/lib/schedule/ScheduledTask.js
Labels: Meta: Documentation

#722 Fix Settings references in the docs
  guides/.docconfig.json
  guides/Getting Started/SettingsGuide.md
Labels: Meta: Documentation, Mod: SettingsGateway, Status: WIP

#715 Changed `RichDisplayRunOptions.time` docs
  src/lib/util/RichDisplay.js
Labels: Meta: Documentation, SEM: N/A

#714 typings: Make Task#run's data field be optional
  typings/index.d.ts
Labels: Meta: Typings, SEM: N/A

#732 add code for proper teams support dependent on d.js imp
  src/events/onceReady.js
Labels: Meta: Feature, SEM: Minor, Status: Blocked, Type: Enhancement
