Repository dirigeants/klasa, pull requests merged in 2019-05, with the labels that each got.

#683 Abort the prompt if the user retypes the command
  src/events/onceReady.js
  src/lib/Client.js
  src/lib/extensions/KlasaMessage.js
  src/lib/usage/TextPrompt.js
  src/monitors/commandHandler.js
Labels: Meta: Feature, Meta: Refactor, Mod: Usage, SEM: Major, Status: Needs Typings, Type: Enhancement

#693 Reword invite command's description to make it clearer
  src/languages/en-US.js
Labels: SEM: Patch, Type: Typo

#694 seperate argumentError from commandError
  src/events/argumentError.js
  src/lib/Client.js
  src/monitors/commandHandler.js
  typings/index.d.ts
Labels: Meta: Feature, SEM: Major, Type: Enhancement

#695 Add Monitor#allowedTypes
  src/lib/structures/Monitor.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Feature, SEM: Minor, Type: Enhancement

#692 initial teams support
  guides/Getting Started/UnderstandingPermissionLevels.md
  src/events/onceReady.js
  src/finalizers/commandCooldown.js
  src/inhibitors/cooldown.js
  src/inhibitors/hidden.js
  src/inhibitors/slowmode.js
  src/lib/Client.js
  src/lib/structures/Monitor.js
  src/lib/util/constants.js
  typings/index.d.ts
Labels: Meta: Feature, SEM: Major

#689 remove client from Piece constructors
  src/lib/structures/Command.js
  src/lib/structures/Event.js
  src/lib/structures/Extendable.js
  src/lib/structures/Inhibitor.js
  src/lib/structures/Monitor.js
  src/lib/structures/base/AliasPiece.js
  src/lib/structures/base/Piece.js
  src/lib/structures/base/Store.js
  typings/index.d.ts
Labels: Meta: Cleanup, Meta: Refactor, Mod: Loader, SEM: Major

#682 Text Prompt Rework
  src/events/argumentError.js
  src/events/onceReady.js
  src/lib/Client.js
  src/lib/extensions/KlasaMessage.js
  src/lib/structures/Command.js
  src/lib/usage/TextPrompt.js
  src/lib/util/constants.js
  src/monitors/commandHandler.js
  typings/index.d.ts
Labels: Meta: Refactor, Mod: Usage, SEM: Major, Status: Ready To Merge, Type: Enhancement

#688 rename event files that have core klasa functionality
  src/events/coreGuildCreate.js
  src/events/coreGuildDelete.js
  src/events/coreMessage.js
  src/events/coreMessageDelete.js
  src/events/coreMessageDeleteBulk.js
  src/events/coreMessageUpdate.js
  src/events/coreSettingsUpdateEntry.js
Labels: Mod: Loader, SEM: Major, Status: Needs Docs, Status: Review Ready

#700 Convert .pluck and .resolve To Return Arrays
  src/lib/settings/SettingsFolder.js
  typings/index.d.ts
Labels: Mod: SettingsGateway, SEM: Major, Type: Enhancement

#698 Settings Guides
  guides/.docconfig.json
  guides/Advanced SettingsGateway/SettingsGatewayKeyTypes.md
  guides/Advanced SettingsGateway/SettingsGatewaySettingsUpdate.md
  guides/Advanced SettingsGateway/UnderstandingSchemaEntries.md
  guides/Advanced SettingsGateway/UnderstandingSchemaFolders.md
  guides/Getting Started/Settings.md
  guides/Getting Started/UnderstandingSettingsGateway.md
Labels: Meta: Documentation, Mod: SettingsGateway
