Repository dirigeants/klasa, pull requests merged in 2019-03, with the labels that each got.

#607 stupid edit returns a clone
  src/lib/util/ReactionHandler.js
  src/lib/util/RichDisplay.js
Labels: Meta: BugFix, Priority: Medium, SEM: Patch

#616 Typings: Fix CommandUsage typings.
  typings/index.d.ts
Labels: Meta: BugFix, Meta: Typings, Priority: Low, SEM: N/A

#574 Environment Variables
  guides/Getting Started/faq.md
Labels: Meta: Documentation, Priority: Low, SEM: N/A, Status: Changes Requested

#620 Make RichDisplay and ReactionHandler classes compatible with custom emojis
  src/lib/util/ReactionHandler.js
  src/lib/util/RichDisplay.js
Labels: Meta: BugFix, Priority: Medium, SEM: Patch
